# Simple Ansible playbook for deployment
# Process still needs to be started manually (TODO)
---
- hosts: vps2
  vars:
    dir_name: /opt/ciptn-hook

  tasks:
  - name: checkout ciptn-hook from Github
    git:
      repo: https://github.com/ps-aux/ciptn-hook.git
      dest: '{{ dir_name }}'

  - name: install node dependencies
    npm: path={{ dir_name }}

    #TODO run/ stop (make service)
  - name: open port
    firewalld:
      zone: public
      port: 3000/tcp
      state: enabled
      permanent: true
      immediate: true

